export const unitsOfMeasurement = [
  // 🔹 General Units
  { name: 'Piece', abr: 'pc' },
  { name: 'Dozen', abr: 'dz' },
  { name: 'Pair', abr: 'pr' },
  { name: 'Pack', abr: 'pk' },
  { name: 'Box', abr: 'bx' },
  { name: 'Bottle', abr: 'btl' },
  { name: 'Bag', abr: 'bag' },
  { name: 'Carton', abr: 'ctn' },
  { name: 'Sachet', abr: 'sct' },
  { name: 'Roll', abr: 'roll' },
  { name: 'Bundle', abr: 'bdl' },

  // 🔹 Weight-based units
  { name: 'Kilogram', abr: 'kg' },
  { name: 'Gram', abr: 'g' },
  { name: 'Milligram', abr: 'mg' },
  { name: 'Tonne', abr: 't' },

  // 🔹 Volume-based units
  { name: 'Litre', abr: 'L' },
  { name: 'Millilitre', abr: 'ml' },
  { name: 'Cubic Meter', abr: 'm³' },
  { name: 'Cubic Centimeter', abr: 'cm³' },

  // 🔹 Length-based units
  { name: 'Meter', abr: 'm' },
  { name: 'Centimeter', abr: 'cm' },
  { name: 'Millimeter', abr: 'mm' },
  { name: 'Kilometer', abr: 'km' },
  { name: 'Inch', abr: 'in' },
  { name: 'Foot', abr: 'ft' },
  { name: 'Yard', abr: 'yd' },
  { name: 'Mile', abr: 'mi' },

  // 🔹 Predefined Package Weights (Grams)
  { name: '10 Grams', value: 10, abr: '10g' },
  { name: '20 Grams', value: 20, abr: '20g' },
  { name: '30 Grams', value: 30, abr: '30g' },
  { name: '40 Grams', value: 40, abr: '40g' },
  { name: '50 Grams', value: 50, abr: '50g' },
  { name: '60 Grams', value: 60, abr: '60g' },
  { name: '70 Grams', value: 70, abr: '70g' },
  { name: '80 Grams', value: 80, abr: '80g' },
  { name: '90 Grams', value: 90, abr: '90g' },
  { name: '100 Grams', value: 100, abr: '100g' },
  { name: '120 Grams', value: 120, abr: '120g' },
  { name: '150 Grams', value: 150, abr: '150g' },
  { name: '180 Grams', value: 180, abr: '180g' },
  { name: '200 Grams', value: 200, abr: '200g' },
  { name: '250 Grams', value: 250, abr: '250g' },
  { name: '300 Grams', value: 300, abr: '300g' },
  { name: '400 Grams', value: 400, abr: '400g' },
  { name: '500 Grams', value: 500, abr: '500g' },
  { name: '750 Grams', value: 750, abr: '750g' },
  { name: '1 Kilogram', value: 1, abr: '1kg' },
  { name: '2 Kilograms', value: 2, abr: '2kg' },
  { name: '5 Kilograms', value: 5, abr: '5kg' },
  { name: '10 Kilograms', value: 10, abr: '10kg' },
  { name: '25 Kilograms', value: 25, abr: '25kg' },
  { name: '50 Kilograms', value: 50, abr: '50kg' },

  // 🔹 Predefined Package Volumes (Millilitres & Litres)
  { name: '10 Millilitres', value: 10, abr: '10ml' },
  { name: '20 Millilitres', value: 20, abr: '20ml' },
  { name: '30 Millilitres', value: 30, abr: '30ml' },
  { name: '40 Millilitres', value: 40, abr: '40ml' },
  { name: '50 Millilitres', value: 50, abr: '50ml' },
  { name: '60 Millilitres', value: 60, abr: '60ml' },
  { name: '70 Millilitres', value: 70, abr: '70ml' },
  { name: '80 Millilitres', value: 80, abr: '80ml' },
  { name: '90 Millilitres', value: 90, abr: '90ml' },
  { name: '100 Millilitres', value: 100, abr: '100ml' },
  { name: '120 Millilitres', value: 120, abr: '120ml' },
  { name: '150 Millilitres', value: 150, abr: '150ml' },
  { name: '180 Millilitres', value: 180, abr: '180ml' },
  { name: '200 Millilitres', value: 200, abr: '200ml' },
  { name: '250 Millilitres', value: 250, abr: '250ml' },
  { name: '300 Millilitres', value: 300, abr: '300ml' },
  { name: '350 Millilitres', value: 350, abr: '350ml' },
  { name: '400 Millilitres', value: 400, abr: '400ml' },
  { name: '450 Millilitres', value: 450, abr: '450ml' },
  { name: '500 Millilitres', value: 500, abr: '500ml' },
  { name: '600 Millilitres', value: 600, abr: '600ml' },
  { name: '700 Millilitres', value: 700, abr: '700ml' },
  { name: '750 Millilitres', value: 750, abr: '750ml' },
  { name: '800 Millilitres', value: 800, abr: '800ml' },
  { name: '900 Millilitres', value: 900, abr: '900ml' },
  { name: '1 Litre', value: 1, abr: '1L' },
  { name: '1.5 Litres', value: 1.5, abr: '1.5L' },
  { name: '2 Litres', value: 2, abr: '2L' },
  { name: '3 Litres', value: 3, abr: '3L' },
  { name: '5 Litres', value: 5, abr: '5L' },
  { name: '10 Litres', value: 10, abr: '10L' },
  { name: '20 Litres', value: 20, abr: '20L' },
  { name: '25 Litres', value: 25, abr: '25L' },
];
